version: '3.8'

services:
  web:
    build: .
    # Inicializa o servidor na porta padrão estabelecida.
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # Injeta todas as variáveis de segurança no container.
    env_file:
      - .env