# Generated by Django 6.0.8 on 2026-09-04 01:32

import apps.academico.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0007_alter_logrecuperacaosenha_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.IntegerField(default=apps.academico.models.ano_atual)),
                ('turno', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10)),
                ('professor_regente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.professor')),
            ],
            options={
                'db_table': 'turmas',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('professor', models.ManyToManyField(to='usuarios.professor')),
                ('turmas', models.ManyToManyField(to='academico.turma')),
            ],
            options={
                'db_table': 'disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ATIVA', 'Matricula Ativa'), ('TRANSFERIDA', 'Transferida'), ('CANCELADA', 'Cancelada'), ('CONCLUIDA', 'Concluida')], default='ATIVA', max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='usuarios.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.turma')),
            ],
            options={
                'db_table': 'matriculas',
                'unique_together': {('aluno', 'turma')},
            },
        ),
    ]
