# Generated by Django 6.0.8 on 2026-08-30 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_otp_ativdo_usuario_otp_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='otp_ativdo',
            new_name='otp_ativado',
        ),
    ]
