# Generated by Django 6.0.8 on 2026-08-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_otp_ativdo_usuario_otp_ativado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tentativas_login',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_login_falha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
