# Generated by Django 6.0.8 on 2026-09-04 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_bloqueado_ate_usuario_tentativas_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecuperacaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=50)),
                ('token_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_recuperacao_senha',
            },
        ),
    ]
