# Generated by Django 6.0.8 on 2026-09-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_logrecuperacaosenha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrecuperacaosenha',
            name='evento',
            field=models.CharField(choices=[('SOLICITACAO', 'Solicitação de recuperação de senha'), ('SUCESSO', 'Recuperação de senha bem-sucedida'), ('FALHA_TOKEN_EXPIRADO', 'Token de recuperação de senha expirado'), ('FALHA_TOKEN_INVALIDO', 'Token de recuperação de senha inválido')], max_length=50),
        ),
    ]
