# Generated by Django 6.0.8 on 2026-09-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_logrecuperacaosenha_evento'),
        ('usuarios', '0007_tokenrecuperacaosenha'),
    ]

    operations = [
    ]
