# Generated by Django 6.0.8 on 2026-09-12 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_merge_20260906_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimentoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('USO_IMAGEM', 'Uso de imagem em comunicados escolares'), ('COMUNICACAO_WHATSAPP', 'Envio de comunicados por WhatsApp')], max_length=30)),
                ('aceito', models.BooleanField()),
                ('versao_termos', models.CharField(default='1.0', max_length=10)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consentimentos_usuario',
            },
        ),
    ]
