# Generated by Django 6.0.8 on 2026-09-19 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_aluno_data_nascimento_alter_aluno_endereco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('LOGIN_FALHA', 'Falha de login'), ('LOGIN_SUCESSO', 'Login bem-sucedido'), ('CONTA_BLOQUEADA', 'Conta bloqueada devido a múltiplas tentativas de login falhas'), ('2FA_SUCESSO', 'Autenticação de dois fatores bem-sucedida'), ('2FA_FALHA', 'Falha na autenticação de dois fatores')], max_length=50)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_acesso',
            },
        ),
    ]
