# Generated by Django 6.0.8 on 2026-09-19 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_logacesso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logacesso',
            old_name='usario',
            new_name='usuario',
        ),
    ]
